name: Auto tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test
          - second_test

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements
      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest marketplace_api_test\test_marketplace_api.py
      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest marketplace_api_test\test_marketplace_api_indexes.py

